#!/usr/bin/env node

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const OUTPUT_PATH = path.join(
  ROOT,
  "packages/core/src/law-snapshot-anchors.generated.ts",
);

const SOURCES = [
  {
    sourceId: "cosmetics-act",
    anchorsPath:
      "policies/law_snapshots/cosmetics-act/versions/2026-04-02/anchors.json",
  },
  {
    sourceId: "enforcement-decree",
    anchorsPath:
      "policies/law_snapshots/enforcement-decree/versions/2026-03-10/anchors.json",
  },
  {
    sourceId: "enforcement-rule",
    anchorsPath:
      "policies/law_snapshots/enforcement-rule/versions/2025-08-01/anchors.json",
  },
];

function readAnchors(relativePath) {
  const absolutePath = path.join(ROOT, relativePath);
  return JSON.parse(readFileSync(absolutePath, "utf8")).anchors ?? [];
}

const anchorMap = Object.fromEntries(
  SOURCES.map(({ sourceId, anchorsPath }) => [sourceId, readAnchors(anchorsPath)]),
);

const fileContents = `import type { LawAnchorRecord } from "../../shared-types/src/index.js";

// Generated by scripts/generate_law_snapshot_anchor_module.mjs
export const LAW_SNAPSHOT_ANCHORS: Record<string, LawAnchorRecord[]> = ${JSON.stringify(
  anchorMap,
  null,
  2,
)};
`;

writeFileSync(OUTPUT_PATH, fileContents);
console.log(`Generated ${path.relative(ROOT, OUTPUT_PATH)}`);
